from typing import Dict, Any, Optional

class MockLLMInterface:
    """
    A mock interface for interacting with a Large Language Model (LLM)
    to generate, mutate, or combine trading strategy code.
    In a real implementation, this would make API calls to an LLM service.
    """
    def __init__(self, api_key: Optional[str] = "mock_api_key", model_name: str = "mock_model_v1"):
        self.api_key = api_key
        self.model_name = model_name
        print(f"MockLLMInterface initialized with model: {self.model_name}")

    def generate_strategy_code(self, prompt: str, initial_template: Optional[str] = None) -> str:
        """
        Simulates generating strategy code from a prompt.
        Args:
            prompt (str): The prompt describing the desired strategy.
            initial_template (str, optional): An initial code template to be filled or modified by the LLM.
        Returns:
            str: A string containing mock Python strategy code.
        """
        print(f"MockLLMInterface: Received prompt to generate strategy: '{prompt[:50]}...'")
        
        mock_strategy_code = f"""
# Strategy generated by MockLLMInterface based on prompt: {prompt}
# Model: {self.model_name}

from algo_trading_framework.src.strategies.base_strategy import BaseStrategy
from algo_trading_framework.src.core.models import Signal, Candle
from algo_trading_framework.src.core.enums import TradeType, OrderType
import pandas as pd
import random # For mock logic

class LLMGeneratedStrategy(BaseStrategy):
    def __init__(self, strategy_name: str = "LLMStrategy", params: dict = None):
        super().__init__(strategy_name, params or {{"symbol": "LLM_SYMBOL"}})
        self.symbol = self.params.get("symbol", "LLM_DEFAULT_SYMBOL")
        self.buy_threshold = random.uniform(0.1, 0.9) # Example of LLM "deciding" a parameter

    def on_bar(self, current_candle: Candle, historical_data: pd.DataFrame) -> Optional[Signal]:
        # Mock logic: Randomly generate a signal
        if random.random() < self.buy_threshold / 10: # Low probability for action
            trade_type = random.choice([TradeType.BUY, TradeType.SELL])
            comment = f"Mock LLM signal: {trade_type.value} triggered randomly with threshold {self.buy_threshold:.2f}"
            print(f"LLMGeneratedStrategy ({self.symbol}): {comment} at {current_candle.timestamp}")
            return Signal(
                timestamp=current_candle.timestamp,
                symbol=self.symbol,
                trade_type=trade_type,
                order_type=OrderType.MARKET,
                quantity=random.randint(1, 5),
                comment=comment
            )
        return None
"""
        return mock_strategy_code

    def mutate_strategy_code(self, existing_code: str, prompt: str) -> str:
        """
        Simulates mutating existing strategy code based on a prompt.
        Args:
            existing_code (str): The Python code of the existing strategy.
            prompt (str): The prompt describing the desired mutation.
        Returns:
            str: A string containing the mock mutated Python strategy code.
        """
        print(f"MockLLMInterface: Received prompt to mutate strategy: '{prompt[:50]}...'")
        
        mutation_comment = f"# Code mutated by MockLLMInterface based on: {prompt}\n"
        mutated_code = mutation_comment + existing_code
        
        # Example simple mutation: add a random parameter or print statement
        if "add a parameter" in prompt.lower():
             mutated_code = mutated_code.replace(
                "self.buy_threshold = random.uniform(0.1, 0.9)", 
                "self.buy_threshold = random.uniform(0.1, 0.9)\n        self.sell_threshold = random.uniform(0.1, 0.9) # Added by mutation"
            )
        elif "logging" in prompt.lower():
            mutated_code = mutated_code.replace(
                "return None",
                "print(f'LLMStrategy ({self.symbol}): No signal at {current_candle.timestamp}')\n        return None"
            )
            
        return mutated_code

    def combine_strategy_codes(self, code_a: str, code_b: str, prompt: str) -> str:
        """
        Simulates combining two existing strategy codes based on a prompt.
        Args:
            code_a (str): Python code of the first strategy.
            code_b (str): Python code of the second strategy.
            prompt (str): The prompt describing how to combine them.
        Returns:
            str: A string containing the mock combined Python strategy code.
        """
        print(f"MockLLMInterface: Received prompt to combine strategies: '{prompt[:50]}...'")
        
        # Very naive combination: append one to another with comments
        combined_code = f"""
# Strategy A (first part of combination by MockLLMInterface based on: {prompt})
# Model: {self.model_name}
{code_a}

# Strategy B (second part of combination by MockLLMInterface)
# {code_b}

# Note: This is a mock combination. A real LLM would attempt a more meaningful merge.
# For example, one might take entry from A and exit from B.
# This mock simply concatenates for structural demonstration.

class CombinedStrategy(BaseStrategy): # Placeholder for a combined class
    def __init__(self, strategy_name: str = "CombinedLLMStrategy", params: dict = None):
        super().__init__(strategy_name, params or {{"symbol": "COMBINED_SYMBOL"}})
        # Potentially initialize components from A and B
        self.strategy_a_logic = None # Placeholder for logic from A
        self.strategy_b_logic = None # Placeholder for logic from B

    def on_bar(self, current_candle: Candle, historical_data: pd.DataFrame) -> Optional[Signal]:
        # Mock: Randomly choose to act like A or B, or a new combined logic
        print(f"CombinedStrategy ({self.params.get('symbol')}): Deciding on action at {current_candle.timestamp}")
        if random.random() < 0.05:
             return Signal(timestamp=current_candle.timestamp, symbol=self.params.get('symbol'),
                           trade_type=random.choice([TradeType.BUY, TradeType.SELL]),
                           order_type=OrderType.MARKET, quantity=1, comment="Combined mock signal")
        return None
"""
        return combined_code

# Example Usage
if __name__ == '__main__':
    llm_interface = MockLLMInterface()
    
    print("\n--- Generating Strategy ---")
    generated_code = llm_interface.generate_strategy_code("Create a simple trend-following strategy for AAPL.")
    print(generated_code[:500] + "\n...") # Print first 500 chars

    print("\n--- Mutating Strategy ---")
    mutated_code = llm_interface.mutate_strategy_code(generated_code, "Add more aggressive logging to the entry conditions.")
    print(mutated_code[:600] + "\n...")

    print("\n--- Combining Strategies ---")
    code1 = "class StrategyOne:\n    def on_tick(self): print('Strat 1 entry')"
    code2 = "class StrategyTwo:\n    def on_exit(self): print('Strat 2 exit')"
    combined = llm_interface.combine_strategy_codes(code1, code2, "Use entry from Strat1 and exit from Strat2.")
    print(combined[:600] + "\n...")
